version: "3"
services:
  art:
    build: .
    command: "npm start"
    environment:
      - NODE_ENV=production
    volumes:
      - ./config:/app/config
      - ./db:/app/db
      - ./static:/app/static
    working_dir: /app


